version: '2'

services:
    nuxt:
        image: node:latest
        command: npm run dev
        working_dir: /app
        ports:
            - 3000:
        environment:
            - NUXT_HOST=0.0.0.0
            - NUXT_PORT=3000
            - REDIS_URL=redis://redis:6379
            - CLIENT_URL=http://localhost:3000
        volumes:
            - .:/app
        depends_on:
            - redis
        networks:
            default:
            internal:

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            internal:

networks:
    default:
    internal:
        internal: true
